apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
nameSuffix: -v1
commonLabels:
  variant: production 
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am staging!
bases:
- ../../base
configMapGenerator:
- name: the-map
  behavior: merge
  files:
  - spawner_ui_config.yaml
