apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
nameSuffix: -v1
commonLabels:
  variant: staging
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am staging!
resources:
- ../../base
configMapGenerator:
- name: my-map
  files:
  - spawner_ui_config.yaml
patchesStrategicMerge:
- map.yaml
