bases:
- ../../base
patchesStrategicMerge:
- deployment.yaml
namePrefix: staging-
configMapGenerator:
- name: ldap-configmap
  behavior: replace
  files:
  - config.env
secretGenerator:
  - name: app-tls
    files:
      - "tls.cert"
      - "tls.key"
    type: "kubernetes.io/tls"

